'use strict';

const del = require('del');
const vinylPaths = require('vinyl-paths');
const path = require('path');
const runSequence = require('run-sequence');

function generate(gulp, config, gulptraum) {

  const outputFolderPath = path.resolve(config.paths.root, config.paths.output);

  gulptraum.task('build-typescript-clean', {
    help: 'Cleans the files compiled from your TypeScript source code'
  }, () => {
    // TODO: make use of excludes provided in the config
    return gulp.src(`${outputFolderPath}`)
      .pipe(vinylPaths(del));
  });

  gulptraum.task('clean-typescript', {
    help: 'Cleans all files generated by the TypeScript plugin'
  }, (callback) => {

    const runSequenceWithGulp = runSequence.use(gulp);
    return runSequenceWithGulp(
      'build-typescript-clean',
      'test-typescript-clean',
      'doc-typescript-clean',
      callback
    );
  });

}

module.exports.generate = generate;
