'use strict';

const del = require('del');
const vinylPaths = require('vinyl-paths');
const path = require('path');
const runSequence = require('run-sequence');

function generate(gulp, config, gulptraum) {

  const outputFolderPath = path.resolve(config.paths.root, config.paths.output);

  gulptraum.task('build-sass-clean', {
    help: 'Cleans all css files built by the SASS plugin'
  }, () => {
    // TODO: make use of excludes provided in the config
    return gulp.src(`${outputFolderPath}/**/*.css`)
      .pipe(vinylPaths(del));
  });

  gulptraum.task('clean-sass', {
    help: 'Cleans all files generated by the SASS plugin'
  }, (callback) => {

    const runSequenceWithGulp = runSequence.use(gulp);
    return runSequenceWithGulp(
      'build-sass-clean',
      callback
    );
  });

}

module.exports.generate = generate;
